name: CI Test

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [  Moose64-9.0, Moose64-10 ]
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - uses: addnab/docker-run-action@v3
        with:
          registry: hub.docker.io
          image:  badetitou/verveinej:v3.0.0
          options: -v ${{ github.workspace }}:/src
          run: |
            cd tests
            /VerveineJ-3.0.0/verveinej.sh  -format json -o output.json -alllocals -anchor assoc .
            cd ..
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 15
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
